#define BitsInt             sizeof(int)
#define IntToBit(v)         ( v ? 1 : 0)
#define SetBit(A,k)         ( A[(k/BitsInt)] |= (1 << (k%BitsInt)) )
#define ClearBit(A,k)       ( A[(k/BitsInt)] &= ~(1 << (k%BitsInt)) )
#define GetBit(A,k)         (IntToBit( A[(k/BitsInt)] & (1 << (k%BitsInt)) ))
#define InvertBit(A,k)      ( A[(k/BitsInt)] ^= (1 << (k%BitsInt)) )
#define AssignBit(A,k,v)   ( v ? SetBit(A,k) : ClearBit(A,k))
